### ISSUE TITLE
Cannot render razor templates from a referenced project

### ISSUE THREAD

**Issue by liamdawson** [aspnet/Mvc#5940]
When upgrading from the preview2 tooling, I've discovered that I now cannot include another project and run its server, and render razor templates from it.

Here's a minimal reproduction: https://github.com/liamdawson/min-razor-repro

I was able to successfully do this in the preview2 tooling. Now, instead, I get this error message:
![image](https://cloud.githubusercontent.com/assets/760143/23773835/166671e0-0575-11e7-8c9d-76fbec42f3eb.png)

**Comment by liamdawson** [comment]
Still haven't found a solution for this issue - any help?

**Comment by pranavkm** [comment]
Changing the working directory, doesn't really changing the application base path. So things like search paths for binaries and the deps file continue to be based off `MinRepro.Host`s output path. However, changing the working directory does cause Hosting \ Mvc to treat `MinRepro` as the entry assembly. Consequently we look for the `MinRepro.deps.json` in `MinRepro.Host`s output path (which does not exist). 

You could add a post build step to the host to copy it in `cp ..\MinRepro\bin\$(Configuration)\MinRepro.deps.json $(OutputPath)` and that should help here.

**Comment by liamdawson** [comment]
Okay, thanks.

In the specific case of the project I'm working on, this issue arises when I'm trying to compile a razor view to a string. I'm using the sample from entropy ( https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs ), and it comes up with the same errors when trying to render cross-project, despite me copying the deps file over. Any pointers on how to give it the info it needs to render correctly?

**Comment by pranavkm** [comment]
@liamdawson explicitly calling the view engine (which is essentially what `RazorViewToStringRendered` does) shouldn't change the compilation. Could you get me a repro application once you've tried out the post build step I have? Alternatively, you could use Razor precompilation to compile views as part of building \ packing `MinRepro`. https://github.com/aspnet/MvcPrecompilation#enabling-view-compilation has some instructions on how to compile files as part of build and https://github.com/aspnet/MvcPrecompilation/blob/rel/1.1.1/testapps/ClassLibraryWithPrecompiledViews/ClassLibraryWithPrecompiledViews.csproj shows it working to pack the generated precompiled view as part of the package.

**Comment by pranavkm** [comment]
Closing this for now. Feel free to reopen once you've had a chance to look at my suggestions here https://github.com/aspnet/Mvc/issues/5940#issuecomment-315431242

**Comment by genifycom** [comment]
[ConsoleRazor.zip](https://github.com/aspnet/Mvc/files/2224371/ConsoleRazor.zip)

I am getting "One or more compilation failures occurred:
4bbzmoty.fa3(4,41): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
4bbzmoty.fa3(5,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
4bbzmoty.fa3(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
etc....

in just this single Console app using DotNet 2.1

I am also trying to get this to work in a DotNet Core 2.1 Library so that I can call it from Test (and from an AWS Lambda Function) but no luck so far.

This is because in a high use scenario (which I have), it takes too long to fire up the whole web server and routing. What is needed is a quick, fast single Razor function page. That way, a component can be created that renders a single page with no routing required (routing is done by API Gateway).

Any help would be greatly appreciated as I have to find a solution.
Ultimately, the pre-compiled Razor page is the solution, but I have yet to find a Console app that can render from a Views.DLL am I missing a sample?

Thanks
